project = "yorgun"

# only services listed here will be reported
[[services]]
name = "backend"
critical = true

[[services]]
name = "postgres"
critical = true

[[services]]
name = "redis"
critical = true

[[services]]
name = "pgadmin"
critical = false # low severity example

